name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Keystore metadata
      KEY_ALIAS: swamprabbit
      KEY_DNAME: "CN=Swamp Rabbit, OU=Dev, O=You, L=City, ST=State, C=US"

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Setup Node.js & install JS deps
      - uses: actions/setup-node@v3
        with:
          node-version: '18'                # Recommended to pin your Node version 8
      - run: yarn install --frozen-lockfile

      # 3. Setup Java 17
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'                # Android Gradle Plugin now targets Java 17+ 9

      # 4. Install Android SDK + build tools
      - uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true  # Must accept SDK licenses before use
          cmdline-tools-version: 9477386     # CLI tools version “9.0” long build number 10
          packages: "platform-tools platforms;android-33 build-tools;33.0.0"

      # 5. Generate & export a random keystore password
      - run: echo "KEYSTORE_PASS=$(openssl rand -hex 16)" >> $GITHUB_ENV

      # 6. Create an ephemeral JKS keystore
      - run: |
          mkdir -p android/app
          keytool -genkeypair \
            -v \
            -keystore android/app/my-release-key.jks \
            -alias $KEY_ALIAS \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass $KEYSTORE_PASS \
            -keypass   $KEYSTORE_PASS \
            -dname     "$KEY_DNAME"

      # 7. Configure Gradle for signing
      - run: |
          cat <<EOF >> android/gradle.properties
          MYAPP_UPLOAD_STORE_FILE=my-release-key.jks
          MYAPP_UPLOAD_KEY_ALIAS=$KEY_ALIAS
          MYAPP_UPLOAD_STORE_PASSWORD=$KEYSTORE_PASS
          MYAPP_UPLOAD_KEY_PASSWORD=$KEYSTORE_PASS
          EOF

      # 8. Ensure gradlew is executable
      - run: chmod +x android/gradlew

      # 9. Build the APK
      - working-directory: android
        run: ./gradlew clean assembleRelease

      # 10. Upload the artifact
      - uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
