name: Build Android APK (Ephemeral Keystore)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEY_ALIAS: swamprabbit      # fixed alias
      KEY_DNAME: "CN=Swamp Rabbit, OU=Dev, O=You, L=City, ST=State, C=US"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Generate a random keystore password
      - name: Generate random password
        id: genpw
        run: |
          echo "::set-output name=PASS::$(openssl rand -hex 16)"

      # 2. Create a new keystore with that password
      - name: Create ephemeral keystore
        run: |
          mkdir -p android/app
          keytool -genkeypair \
            -v \
            -keystore android/app/my-release-key.jks \
            -alias $KEY_ALIAS \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass ${{ steps.genpw.outputs.PASS }} \
            -keypass   ${{ steps.genpw.outputs.PASS }} \
            -dname     "$KEY_DNAME"

      # 3. Setup JDK 11
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # … (Android SDK install, caches, npm/Yarn install) …

      # 4. Inject the dynamic password into gradle.properties
      - name: Configure signing in Gradle
        run: |
          cat <<EOF >> android/gradle.properties
          MYAPP_UPLOAD_STORE_FILE=my-release-key.jks
          MYAPP_UPLOAD_KEY_ALIAS=$KEY_ALIAS
          MYAPP_UPLOAD_STORE_PASSWORD=${{ steps.genpw.outputs.PASS }}
          MYAPP_UPLOAD_KEY_PASSWORD=${{ steps.genpw.outputs.PASS }}
          EOF

      # 5. Build the APK
      - name: Build Release APK
        working-directory: android
        run: ./gradlew clean assembleRelease

      # 6. Upload APK
      - uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
