name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEY_ALIAS: swamprabbit
      KEY_DNAME: "CN=Swamp Rabbit, OU=Dev, O=You, L=City, ST=State, C=US"

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install JS dependencies with Yarn
      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      # 4. Setup Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 5. Install Android SDK components
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            'platforms;android-33'
            'build-tools;33.0.0'
            'platform-tools'
            'cmdline-tools;latest'
          cmdline-tools-version: latest
          accept-android-sdk-licenses: true

      # 6. Generate and export a random keystore password
      - name: Generate random keystore password
        run: echo "KEYSTORE_PASS=$(openssl rand -hex 16)" >> $GITHUB_ENV

      # 7. Create an ephemeral JKS keystore
      - name: Create ephemeral keystore
        run: |
          mkdir -p android/app
          keytool -genkeypair \
            -v \
            -keystore android/app/my-release-key.jks \
            -alias $KEY_ALIAS \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass $KEYSTORE_PASS \
            -keypass   $KEYSTORE_PASS \
            -dname     "$KEY_DNAME"

      # 8. Wire the keystore into Gradle
      - name: Configure Gradle signing
        run: |
          cat <<EOF >> android/gradle.properties
          MYAPP_UPLOAD_STORE_FILE=my-release-key.jks
          MYAPP_UPLOAD_KEY_ALIAS=$KEY_ALIAS
          MYAPP_UPLOAD_STORE_PASSWORD=$KEYSTORE_PASS
          MYAPP_UPLOAD_KEY_PASSWORD=$KEYSTORE_PASS
          EOF

      # 9. Ensure the Gradle wrapper is executable
      - name: Make Gradle wrapper executable
        run: chmod +x android/gradlew

      # 10. Build the release APK
      - name: Build Release APK
        working-directory: android
        run: ./gradlew clean assembleRelease

      # 11. Upload the signed APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
