name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: $HOME/Android/Sdk
      ANDROID_HOME:     $HOME/Android/Sdk

      KEY_ALIAS: swamprabbit
      KEY_DNAME: "CN=Swamp Rabbit, OU=Dev, O=You, L=City, ST=State, C=US"

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Node.js & JS deps
      - name: Setup Node.js & install deps
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn install --frozen-lockfile

      # 3. JDK 17
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 4. Manual Android SDK Command‑Line Tools install
      - name: Install Android SDK CLT & packages
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

          # Suppress sdkmanager warnings
          mkdir -p $HOME/.android
          touch $HOME/.android/repositories.cfg

          # Download the correct CLI tools (9.0 → long version 9477386) 0
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip \
            -O /tmp/cmdline-tools.zip
          unzip /tmp/cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest

          # Add to PATH
          echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:\$PATH" \
            >> $GITHUB_ENV

          # Install platform-tools, API 33, build-tools 33.0.0
          sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.0"
          yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses

      # 5. Generate & export a keystore password
      - name: Generate keystore password
        run: echo "KEYSTORE_PASS=$(openssl rand -hex 16)" >> $GITHUB_ENV

      # 6. Create ephemeral keystore
      - name: Create ephemeral keystore
        run: |
          mkdir -p android/app
          keytool -genkeypair \
            -v \
            -keystore android/app/my-release-key.jks \
            -alias $KEY_ALIAS \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass $KEYSTORE_PASS \
            -keypass   $KEYSTORE_PASS \
            -dname     "$KEY_DNAME"

      # 7. Wire keystore into Gradle
      - name: Configure Gradle signing
        run: |
          cat <<EOF >> android/gradle.properties
          MYAPP_UPLOAD_STORE_FILE=my-release-key.jks
          MYAPP_UPLOAD_KEY_ALIAS=$KEY_ALIAS
          MYAPP_UPLOAD_STORE_PASSWORD=$KEYSTORE_PASS
          MYAPP_UPLOAD_KEY_PASSWORD=$KEYSTORE_PASS
          EOF

      # 8. Ensure Gradle wrapper is executable
      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # 9. Build the release APK
      - name: Build Release APK
        working-directory: android
        run: ./gradlew clean assembleRelease

      # 10. Upload the signed APK
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
